-- Operator Beetwen
-- digunakan untuk menguji range tertentu 
-- expression [NOT] BETWEEN low AND high

-- Menampilkan data dari 500 - 600
SELECT PRODUCT_NAME, STANDARD_COST FROM PRODUCTS WHERE STANDARD_COST BETWEEN 500 AND 600 ORDER BY STANDARD_COST;
-- Menampilkan data dari 500 - 600
SELECT PRODUCT_NAME, STANDARD_COST FROM PRODUCTS WHERE STANDARD_COST >= 500 AND STANDARD_COST <= 600 ORDER BY STANDARD_COST;
-- Menampilkan data bukan dari 500 - 600
SELECT PRODUCT_NAME, STANDARD_COST FROM PRODUCTS WHERE STANDARD_COST NOT BETWEEN 500 AND 600 ORDER BY STANDARD_COST;
-- Menampilkan data bukan dari 500 - 600
SELECT PRODUCT_NAME, STANDARD_COST FROM PRODUCTS WHERE STANDARD_COST < 500 OR STANDARD_COST > 600 ORDER BY STANDARD_COST;
-- Menampilkan range menggunakan tanggal
SELECT ORDER_ID, CUSTOMER_ID, STATUS, ORDER_DATE FROM ORDERS WHERE ORDER_DATE BETWEEN DATE '2016-12-01' AND DATE '2016-12-31' ORDER BY ORDER_DATE;