-- menggabungkan dua tabel dalam database (SQL) dengan menampilkan semua data dari tabel sebelah kiri,
--  dan hanya data yang cocok dari tabel sebelah kanan

-- SELECT
--      column_list
-- FROM
-- T1
-- LEFT JOIN T2 ON
--      join_predicate;

SELECT ORDER_ID, STATUS, EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME FROM ORDERS
LEFT JOIN EMPLOYEES on EMPLOYEES.EMPLOYEE_ID=ORDERS.SALESMAN_ID
ORDER BY ORDERS.ORDER_DATE;

-- multi table
SELECT ORDER_ID, STATUS, EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME FROM ORDERS
LEFT JOIN EMPLOYEES on EMPLOYEE_ID=ORDERS.SALESMAN_ID
LEFT JOIN CUSTOMERS on CUSTOMERS.CUSTOMER_ID=CUSTOMERS.CUSTOMER_ID
ORDER BY ORDERS.ORDER_DATE;

-- menggunakan using
select NAME, ORDER_ID, STATUS, ORDERS.ORDER_DATE FROM CUSTOMERS
LEFT JOIN ORDERS USING(CUSTOMER_ID)
ORDER BY name;

-- Menambahkan kondisi where (hanya menampilkan data order id bernilai 58)
SELECT ORDER_ID, STATUS, EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.LAST_NAME FROM ORDERS
LEFT JOIN EMPLOYEES on EMPLOYEES.EMPLOYEE_ID=ORDERS.SALESMAN_ID
where ORDERS.ORDER_ID=58;

-- dengan tambahan kondisi join (menampilkan data 58 tetapi menampilkan semua data employee)
SELECT ORDER_ID, STATUS, EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.LAST_NAME FROM ORDERS
LEFT JOIN EMPLOYEES on EMPLOYEES.EMPLOYEE_ID=ORDERS.SALESMAN_ID
and ORDERS.ORDER_ID=58;