-- SELECT 
--  column_list
-- FROM
-- T1
-- RIGHT JOIN T2 ON
-- join_predicate;

SELECT EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME, ORDER_ID, STATUS FROM orders
RIGHT JOIN EMPLOYEES on EMPLOYEES.EMPLOYEE_ID=orders.SALESMAN_ID
order BY EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME;

SELECT name, ORDER_ID, STATUS FROM ORDERS
RIGHT JOIN CUSTOMERS USING(CUSTOMER_ID) ORDER BY name;

SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME, ORDER_ID, STATUS FROM ORDERS
RIGHT JOIN EMPLOYEES on EMPLOYEES.EMPLOYEE_ID=ORDERS.SALESMAN_ID
where EMPLOYEES.EMPLOYEE_ID=57;

SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME, ORDER_ID, STATUS FROM ORDERS
RIGHT JOIN EMPLOYEES on EMPLOYEES.EMPLOYEE_ID=ORDERS.SALESMAN_ID
and EMPLOYEES.EMPLOYEE_ID=57;

SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME, ORDER_ID, STATUS FROM ORDERS
RIGHT JOIN EMPLOYEES on EMPLOYEES.EMPLOYEE_ID=ORDERS.SALESMAN_ID
where ORDERS.ORDER_ID is NULL;

SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME, ORDER_ID, STATUS FROM EMPLOYEES
LEFT JOIN ORDERS on EMPLOYEES.EMPLOYEE_ID=ORDERS.SALESMAN_ID
where ORDERS.ORDER_ID is NULL;